replicaCount: 1

image:
  repository: ashutosh4782/tripkar-mongodb
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 27017

useStatefulSet: false

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 128Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

gateway:
  enabled: true
  className: "eg"

route:
  path: "/"
