{{- if .Values.useStatefulSet }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "booking-service.fullname" . }}
spec:
  serviceName: {{ include "booking-service.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "booking-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "booking-service.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
{{- end }}
