apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "api-gateway.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "api-gateway.fullname" . }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
