replicaCount: 1

image:
  repository: your-dockerhub-username/tripkar-booking-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 5003

useStatefulSet: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

gateway:
  enabled: true
  className: "eg"

route:
  path: "/"
