apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
{{- if .Values.gateway.enabled }}
  parentRefs:
  - name: {{ include "frontend.fullname" . }}-gateway
{{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.route.path }}
    backendRefs:
    - name: {{ include "frontend.fullname" . }}
      port: {{ .Values.service.port }}
